# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/2022jcs/area_competition/encoder_top/encoder_top.srcs/sources_1/ip/axi_convert_256_32/axi_convert_256_32.xci
# IP: The module: 'axi_convert_256_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/axi_convert_256_32/axi_convert_256_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_convert_256_32'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/2022jcs/area_competition/encoder_top/encoder_top.srcs/sources_1/ip/axi_convert_256_32/axi_convert_256_32.xci
# IP: The module: 'axi_convert_256_32' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/axi_convert_256_32/axi_convert_256_32_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'axi_convert_256_32'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
