# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/axi_convert128_64/axi_convert128_64.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_convert128_64 || ORIG_REF_NAME==axi_convert128_64} -quiet] -quiet

# IP: ip/axi_convert_256_32/axi_convert_256_32.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==axi_convert_256_32 || ORIG_REF_NAME==axi_convert_256_32} -quiet] -quiet
