# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/2022jcs/area_competition/encoder_top/encoder_top.srcs/sources_1/ip/ax4_convert/ax4_convert.xci
# IP: The module: 'ax4_convert' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/ax4_convert/ax4_convert_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ax4_convert'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/2022jcs/area_competition/encoder_top/encoder_top.srcs/sources_1/ip/ax4_convert/ax4_convert.xci
# IP: The module: 'ax4_convert' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/ax4_convert/ax4_convert_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ax4_convert'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
