# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/2022jcs/area_competition/encoder_top/encoder_top.srcs/sources_1/ip/fifo_256_256/fifo_256_256.xci
# IP: The module: 'fifo_256_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/fifo_256_256/fifo_256_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256_256'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/fifo_256_256/fifo_256_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/2022jcs/area_competition/encoder_top/encoder_top.srcs/sources_1/ip/fifo_256_256/fifo_256_256.xci
# IP: The module: 'fifo_256_256' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/fifo_256_256/fifo_256_256.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/2022jcs/area_competition/encoder_top/encoder_top.gen/sources_1/ip/fifo_256_256/fifo_256_256_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_256_256'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
